import Head from "next/head";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Growth Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="text-9xl dark:text-white font-thin dark:text-white">
          Home Page
        </p>
      </main>

      <footer></footer>
    </Fragment>
  );
}
