import Head from "next/head";
import Script from 'next/script';

import {Fragment} from "react";

export default function Home() {
    return (
        <Fragment>
            <Head>
                <title>Growth Menu</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css"/>

            </Head>

            <body>
            <p className="text-9xl dark:text-white font-thin dark:text-white">
                Home Page
            </p>




            <Script
                src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"
                strategy="beforeInteractive"
            />
            </body>

            <footer></footer>
        </Fragment>
    );
}
